### ISSUE TITLE
Raspberry Pi 3b with v0.9.8_linuxarmv71 and ArchLinux

### ISSUE THREAD

**Issue by autr** [openframeworks/openFrameworks#5763]
Hello, getting this compile error with Poco in ./install_dependencies.sh

```
ranlib /home/pi/of_v0.9.8_linuxarmv7l/scripts/apothecary/build/poco/lib/Linux/armv7l/libPocoDataSQLite.a
make[1]: Leaving directory '/home/pi/of_v0.9.8_linuxarmv7l/scripts/apothecary/build/poco/Data/SQLite'

 ^ Received error ^

```
OF compiles fine with make Release -C /home/pi/of_v0.9.8_linuxarmv7l/libs/openFrameworksCompiled/project/ complete OK, but with any of the examples;
```

/usr/bin/ld: /home/pi/of_v0.9.8_linuxarmv7l/libs/tess2/lib/linuxarmv7l/libtess2.a(tess.o): relocation R_ARM_THM_MOVW_ABS_NC against `a local symbol' can not be used when making a shared object; recompile with -fPIC
/home/pi/of_v0.9.8_linuxarmv7l/libs/tess2/lib/linuxarmv7l/libtess2.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
make[1]: *** [/home/pi/of_v0.9.8_linuxarmv7l/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:384: bin/3DPrimitivesExample] Error 1
make[1]: Leaving directory '/home/pi/of_v0.9.8_linuxarmv7l/examples/3d/3DPrimitivesExample'
make: *** [/home/pi/of_v0.9.8_linuxarmv7l/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:130: Release] Error 2

```

**Comment by autr** [comment]
On closer inspection

```
src/CipherImpl.cpp:80:21: error: field '_ctx' has incomplete type 'EVP_CIPHER_CTX {aka evp_cipher_ctx_st}'
   EVP_CIPHER_CTX    _ctx;
                     ^~~~
In file included from /usr/include/openssl/crypto.h:31:0,
                 from include/Poco/Crypto/OpenSSLInitializer.h:26,
                 from include/Poco/Crypto/CipherKeyImpl.h:24,
                 from include/Poco/Crypto/CipherKey.h:24,
                 from include/Poco/Crypto/CipherImpl.h:25,
                 from src/CipherImpl.cpp:17:
/usr/include/openssl/ossl_typ.h:90:16: note: forward declaration of 'EVP_CIPHER_CTX {aka struct evp_cipher_ctx_st}'
 typedef struct evp_cipher_ctx_st EVP_CIPHER_CTX;
```

**Comment by autr** [comment]
Related to this I guess? https://github.com/openframeworks/openFrameworks/issues/5397

**Comment by arturoc** [comment]
yes OF 0.9.8 is not compatible with latest gcc versions, please use the nightly builds until 0.10 is released

**Comment by autr** [comment]
Installed with nightly build - closing issue.

**Comment by luni3359** [comment]
What version of gcc should be used to compile? The problem persists.
