### ISSUE TITLE
failed to compile openframeworks on Ubuntu 15.10 due to gstreamer dependency

### ISSUE THREAD

**Issue by avilleret** [openframeworks/openFrameworks#4656]
After upgrading to Ubuntu 15.10, I can't build OpenFrameworks anymore.
Here is the error I got when running `./compileOF.sh` script.
Note that I ran `install_dependencies.sh` script before.

~~~~
In file included from /home/antoine/lib-src/openFrameworks/libs/openFrameworks/video/ofGstVideoPlayer.h:3:0,
                 from /home/antoine/lib-src/openFrameworks/libs/openFrameworks/video/ofGstVideoPlayer.cpp:8:
/home/antoine/lib-src/openFrameworks/libs/openFrameworks/video/ofGstUtils.h:14:29: fatal error: gst/video/video.h: No such file or directory
~~~~

libgstreamer has been updated to version 1.6 with Ubuntu 15.10 (while it was at 1.4.5 with Ubuntu 15.04), maybe this included some changes in include files ?

**Comment by arturoc** [comment]
i'm on ubuntu 15.10 and it works fine for me, what do you get if you run:

```
pkg-config gstreamer-1.0 --cflags
```

**Comment by aspeteRakete** [comment]
They moved the config.h in 1.6. See here: https://github.com/ofnode/of/issues/33

**Comment by arturoc** [comment]
the makefiles use pkgconfig so they should be doing the right thing no matter what

**Comment by avilleret** [comment]
thanks @aspeteRakete I've already see that, but still stuck with video.h

@arturoc :
~~~~
$ pkg-config gstreamer-1.0 --cflags
-pthread -I/usr/include/gstreamer-1.0 -I/usr/lib/x86_64-linux-gnu/gstreamer-1.0/include -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include 
~~~~

but none of them contains a `gst/video/video.h`

maybe I should restart building from scratch

**Comment by arturoc** [comment]
can you try installing libgstreamer-plugins-base1.0-dev

```
sudo apt-get install libgstreamer-plugins-base1.0-dev
```

**Comment by avilleret** [comment]
@arturoc : it's already there for a while

**Comment by avilleret** [comment]
btw, you're right @arturoc, `libgstreamer-plugins-base1.0-dev` does [contains the missing file](http://packages.ubuntu.com/wily/amd64/libgstreamer-plugins-base1.0-dev/filelist)

but I have to reinstall it to fix the issue, and I still don't understand why...

thanks for the prompt reply btw

**Comment by arturoc** [comment]
that's strange not sure what might have happened, i installed everything from scratch on a clean install of ubuntu 15.10 to test and it was working fine so it should have been something specific to your machine.

**Comment by avilleret** [comment]
yep, maybe something wrong happen during the upgrade from 15.04, anyway this is fixed now :-)
