### ISSUE TITLE
osxVideoRecorderExample doesn't build on OS X 10.12.1 due to lack of QTKit

### ISSUE THREAD

**Issue by avilleret** [openframeworks/openFrameworks#5398]
Here is the compiler output (with QtCreator / CMake but I do have the same error with XCode but I don't know how to copy&paste compiler output from XCode)

`````
In file included from /Users/antoinevilleret/dev/of/examples/ofExamples/video/osxVideoRecorderExample/src/main.cpp:2:
/Users/antoinevilleret/dev/of/examples/ofExamples/video/osxVideoRecorderExample/src/ofApp.h:26:9: error: use of undeclared identifier 'ofQTKitGrabber'
                ofPtr<ofQTKitGrabber>   vidRecorder;
                      ^
/Users/antoinevilleret/dev/of/examples/ofExamples/video/osxVideoRecorderExample/src/ofApp.h:30:19: error: unknown type name 'ofVideoSavedEventArgs'
                void videoSaved(ofVideoSavedEventArgs& e);
                                ^
/Users/antoinevilleret/dev/of/examples/ofExamples/video/osxVideoRecorderExample/src/main.cpp:12:2: error: no matching function for call to 'ofRunApp'
        ofRunApp( new ofApp());
        ^~~~~~~~
/Users/antoinevilleret/dev/of/src/openframeworks/app/ofAppRunner.h:50:5: note: candidate function not viable: no known conversion from 'ofApp *' to 'shared_ptr<ofBaseApp>' for 1st argument
int ofRunApp(shared_ptr<ofBaseApp> OFSA);
    ^
/Users/antoinevilleret/dev/of/src/openframeworks/app/ofAppRunner.h:51:5: note: candidate function not viable: no known conversion from 'ofApp *' to 'ofBaseApp *' for 1st argument
int ofRunApp(ofBaseApp * OFSA = nullptr); // will be deprecated
    ^
/Users/antoinevilleret/dev/of/src/openframeworks/app/ofAppRunner.h:52:6: note: candidate function not viable: requires 2 arguments, but 1 was provided
void ofRunApp(shared_ptr<ofAppBaseWindow> window, shared_ptr<ofBaseApp> app);
     ^
3 errors generated.
````

**Comment by arturoc** [comment]
are you using the latest version? this was solved a couple of versions ago

**Comment by arturoc** [comment]
oh just realized you are referring to a specific example. yes that example is not compatible with latest OSx SDK anymore since qtkit has been completely phased out

**Comment by avilleret** [comment]
is there any chance to see this example working without QTKit ?

**Comment by lethalrush** [comment]
Has this been addressed?  I have 0.9.8 release and can't build osxVideoRecorderExample

**Comment by kerstin** [comment]
Wondering about the same thing...
