### ISSUE TITLE
Freeimage 3.17.0 'Undefined symbols for architecture x86_64'

### ISSUE THREAD

**Issue by gameoverhack** [openframeworks/openFrameworks#4385]
On latest master 0.9.0 Xcode 4.x 10.8 SDK I can't compile x64 projects because of:

>Undefined symbols for architecture x86_64:
  "___exp10", referenced from:
      _opj_tcd_rateallocate in freeimage.a(tcd.o-x86_64)
ld: symbol(s) not found for architecture x86_64

Recompiling a universal 32/64bit lib with c++11 support against the 10.8 SDK fixes the problem on my machine. 

@danoli3 maybe the build in #3936 and mentioned in #3925 done against 10.9, 10.10 SDK?

Anyway, I've been out of the game for a while so maybe I just checked out the wrong 0.9.0 or perhaps we dropped support for 10.8 - I'm not sure - but in any case I had to recompile :(

**Comment by arturoc** [comment]
we've had similar problems with other libraries, can you send a PR with the recompiled library? it seems libraries compiled with 10.10 won't work on 10.8

**Comment by gameoverhack** [comment]
It's also possible that libtool builds the lib but doesn't link correctly: http://stackoverflow.com/a/16070483

What version of libtool are you guys using?

Not quite sure how you got it to build on OSX with

```
$(STATICLIB)-ppc: $(MODULES_PPC)
	$(LIBTOOL) -arch_only ppc -o $@ $(MODULES_PPC)

$(STATICLIB)-i386: $(MODULES_I386)
	$(LIBTOOL) -arch_only i386 -o $@ $(MODULES_I386)

$(STATICLIB)-x86_64: $(MODULES_X86_64)
	$(LIBTOOL) -arch_only x86_64 -o $@ $(MODULES_X86_64)
```

But amongst the usual lib compiling PITA, the advice in that SO comment led me to:

```
$(STATICLIB)-ppc: $(MODULES_PPC)
	ar rcs $@ $(MODULES_PPC)

$(STATICLIB)-i386: $(MODULES_I386)
	ar rcs $@ $(MODULES_I386)

$(STATICLIB)-x86_64: $(MODULES_X86_64)
	ar rcs $@ $(MODULES_X86_64)
```

@arturoc no problem

**Comment by arturoc** [comment]
are you using the apothecary script?

**Comment by bakercp** [comment]
I can also recompile if needed.

**Comment by bakercp** [comment]
@arturoc @gameoverhack I've got a recompile on the way.  I'm wondering if we need to recompile freeimage ios for 10.8 as well?

**Comment by arturoc** [comment]
yes i guess so, if you can compile it too?

**Comment by bakercp** [comment]
Yep, I'll do both.


---
http://christopherbaker.net

**Comment by gameoverhack** [comment]
@arturoc no I tried to use the apothecary script (as I needed to figure out how to compile against 10.8) but actually that script (with the patches) didn't work on my machine. Libtool failed on the lines I posted above, and as per that stackoverflow post I had to just use ar instead of libtool to bundle the lib. That post also describes how it's possible for libtool to incorrectly bundle a library in certain cases.

@bakercp sorry i didn't see your post and just issued a pull request as soon as i got online tonight. Feel free to close it if your build is working.

**Comment by geeta-saraswat** [comment]
hey , 

I am trying to compile Freeimage 3.17.0 on yesomite 10.10 
The make file I am using is attached here with . 
but still getting following error 
ibtool: object: ./Source/FreeImage/BitmapAccess.o-x86_64 malformed object (unknown load command 1)
libtool: object: ./Source/FreeImage/ColorLookup.o-x86_64 malformed object (unknown load command 1)
libtool: object: ./Source/FreeImage/FreeImage.o-x86_64 malformed object (unknown load command 1)
libtool: object: ./Source/FreeImage/FreeImageIO.o-x86_64 malformed object (unknown load command 1)
libtool: object: ./Source/FreeImage/GetType.o-x86_64 malformed object (unknown load command 1)
libtool: object: ./Source/FreeImage/MemoryIO.o-x86_64 malformed object (unknown load command 1)
libtool: object: ./Source/FreeImage/PixelAccess.o-x86_64 malformed object (unknown load command 1)
libtool: object: ./Source/FreeImage/J2KHelper.o-x86_64 malformed object (unknown load command 1)
libtool: object: ././Source/FreeImage/MNGHelper.o-x86_64 malformed object (unknown load command 1

Any IDEA

**Comment by danoli3** [comment]
We are currently using this "patched" version of FreeImage 3.17.0 for OSX / iOS. Try that.

Malformed object usually means the compilation errored in some way so check your build logs. @geeta-saraswat

**Comment by geeta-saraswat** [comment]
hey I didn't got , can you please ping the link for that

**Comment by geeta-saraswat** [comment]
@gameoverhack  , I compiled the freeImage on MAC 10.7.2 with Xcode 4.3.3 . The libfreeImage.a generated . 
But when I link this with my application I get following linking error. 
Undefined symbols for architecture i386:
  "___exp10", referenced from:
      _opj_tcd_rateallocate in libfreeimage.a(tcd.o-i386)
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)  

I used this Makefile on Mac 10.7 lion . 
http://sourceforge.net/p/freeimage/bugs/228/attachment/Makefile.osx2 

Any Idea.

**Comment by danoli3** [comment]
__exp10 is only available in 10.9.
Check the min OS X version in your build script and potentially change it to 10.7. Why do you need to support 10.7 though? Seems pretty out of date.
