### ISSUE TITLE
AllAddonsExample doesn't compile on OSX 10.10 ofxTCPServer ofMutex::ScopedLock Error

### ISSUE THREAD

**Issue by rezaali** [openframeworks/openFrameworks#3990]
got many errors of this type: 

ofxTCPServer.cpp:86:11: error: no member named 'ScopedLock' in 'std::__1::mutex'

Proposing to use: std::unique_lock<std::mutex> instead of ScopedLock instead.

**Comment by bilderbuchi** [comment]
Closed by #3993
