### ISSUE TITLE
openssl/opensslconf.h missing in 0.8.4 on OSX

### ISSUE THREAD

**Issue by lab101** [openframeworks/openFrameworks#4515]
The latest official release doesn't compile on osx 10.10.5 with XCode 7.0.1
Also having this on examples which don't rely on urlFileLoader like the emptyExample.

Adding  ../../../../libs/openssl/include to the headersearch paths of OF fixes the issue.

`2/libs/openFrameworks/utils/ofURLFileLoader.cpp:3:
In file included from ../../../../libs/poco/include/Poco/Net/HTTPSClientSession.h:44:
In file included from ../../../../libs/poco/include/Poco/Net/Utility.h:44:
In file included from ../../../../libs/poco/include/Poco/Net/Context.h:45:
In file included from ../../../../libs/poco/include/Poco/Crypto/X509Certificate.h:44:
../../../../libs/poco/include/Poco/Crypto/OpenSSLInitializer.h:45:10: fatal error: 'openssl/opensslconf.h' file not found
#include <openssl/opensslconf.h>
         ^
1 error generated.
`

**Comment by ofZach** [comment]
there's some discussion of this here w/ fixes (this should be fine in 0.9):

http://forum.openframeworks.cc/t/fix-for-xcode-7-and-of-0-8-4-opensslconf-h-not-found/20800

**Comment by bilderbuchi** [comment]
> (this should be fine in 0.9)

closing this as already fixed, then.
