### ISSUE TITLE
Codeblocks (win) Issue with calibinit.cpp; circlesgrid.cpp; lkpyramid.cpp

### ISSUE THREAD

**Issue by redfox14** [openframeworks/openFrameworks#2000]
Hello,
I am working with OF version 0.7.4 and Codeblocks v. 12.11.
I am getting the following 6 linking errors (undefined references):

......\addons\ofxOpenCv\libs\opencv\lib\win_cb\libopencv_calib3d231.a(calibinit.obj):calibinit.cpp:(.text$_ZN2cv15findCirclesGridERKNS_11_InputArrayENS_5Size_IiEERKNS_12_OutputArrayEiRKNS_3PtrINS_15FeatureDetectorEEE+0x1a9)||undefined reference to `cv::FeatureDetector::detect(cv::Mat const&, std::vector<cv::KeyPoint, std::allocator<cv::KeyPoint> >&, cv::Mat const&) const'|
..\..\..\addons\ofxOpenCv\libs\opencv\lib\win_cb\libopencv_calib3d231.a(circlesgrid.obj):circlesgrid.cpp:(.text$_ZN2cv22findCirclesGridDefaultERKNS_11_InputArrayENS_5Size_IiEERKNS_12_OutputArrayEi+0x47)||undefined reference to`cv::SimpleBlobDetector::Params::Params()'|
......\addons\ofxOpenCv\libs\opencv\lib\win_cb\libopencv_calib3d231.a(circlesgrid.obj):circlesgrid.cpp:(.text$_ZN2cv22findCirclesGridDefaultERKNS_11_InputArrayENS_5Size_IiEERKNS_12_OutputArrayEi+0x6f)||undefined reference to `cv::SimpleBlobDetector::SimpleBlobDetector(cv::SimpleBlobDetector::Params const&)'|
..\..\..\addons\ofxOpenCv\libs\opencv\lib\win_cb\libopencv_video231.a(lkpyramid.obj):lkpyramid.cpp:(.text$_ZL25icvInitPyramidalAlgorithmPK5CvMatS1_PS_S2_iP14CvTermCriteriaiiPPPhS7_PPiPP6CvSizePPdPN2cv10AutoBufferIhLj4104EEE.isra.45.constprop.62+0x81c)||undefined reference to`cvPyrDown'|
......\addons\ofxOpenCv\libs\opencv\lib\win_cb\libopencv_video231.a(lkpyramid.obj):lkpyramid.cpp:(.text$_ZL25icvInitPyramidalAlgorithmPK5CvMatS1_PS_S2_iP14CvTermCriteriaiiPPPhS7_PPiPP6CvSizePPdPN2cv10AutoBufferIhLj4104EEE.isra.45.constprop.62+0x944)||undefined reference to `cvPyrDown'|
..\..\..\addons\ofxOpenCv\libs\opencv\lib\win_cb\libopencv_video231.a(lkpyramid.obj):lkpyramid.cpp:(.text$_ZN2cv20calcOpticalFlowPyrLKERKNS_11_InputArrayES2_S2_RKNS_12_OutputArrayES5_S5_NS_5Size_IiEEiNS_12TermCriteriaEdid+0x1649)||undefined reference to`cv::pyrDown(cv::_InputArray const&, cv::_OutputArray const&, cv::Size_<int> const&)'|
