### ISSUE TITLE
OF 0.10.0 and Raspberry Pi 4 Raspbian Buster

### ISSUE THREAD

**Issue by eshkrab** [openframeworks/openFrameworks#6322]
I just got raspberry pi 4 in the mail and wanted to see if somehow miraculously would work with OF10.0 arm6 version. I got pretty far, all things considered, and the empty example compiles, although I am unable to launch the app itself. From what I can tell it's a GL-GLes issue. 

Things I had to change:
When running install_dependencies.sh for debian, an error was thrown trying to install libgles1-mesa-dev and libgles2-mesa-dev and the package manager said to replace the libgles1-mesa-dev with libglvnd-dev. I did and everything compiles after that but I assume that's the cause of app launch failure.
To compile the empty example app (I haven't tried anything else) I had to add -latomic to LD flags in config.make to fix undefined reference to '__atomic_fetch_add_8'

Can anyone point me in the right direction for this quest, or should I just sit tight until Buster support comes out?

**Comment by bakercp** [comment]
Please follow the discussion here https://forum.openframeworks.cc/t/rpi-4-raspbian-buster-openframeworks/32856/3

**Comment by ofTheo** [comment]
This is fixed in master / 0.11.0 release. :)
