### ISSUE TITLE
linux64 opencv libraries are broken

### ISSUE THREAD

**Issue by fx-lange** [openframeworks/openFrameworks#1255]
hey guys,

after pulling from develop (into my fork) two days ago I can't build opencv related projects anymore. today i tested the openCv example with a fresh and clean oF clone on linux32 and linux64. on linux32 everything works fine but on linux64 i still get the following linking error

> ../../../addons/ofxOpenCv/libs/opencv/lib/linux64/libopencv_calib3d.a(circlesgrid.o):
> In function `CirclesGridClusterFinder::hierarchicalClustering(...)':
> circlesgrid.cpp: undefined reference to`std::__detail::_List_node_base::_M_hook(std::__detail::_List_node_base_)'
> circlesgrid.cpp: undefined reference to `std::__detail::_List_node_base::_M_transfer(std::__detail::_List_node_base_, std::__detail::_List_node_base*)'
> collect2: ld returned 1 exit status

or is this a gcc version issue? i'm working on ubuntu 11.04
