### ISSUE TITLE
OF fails to compile on Win 8.1 with VS2015 (whole program optimisation issue with uriparser)

### ISSUE THREAD

**Issue by roxlu** [openframeworks/openFrameworks#5426]
Hey, 

I just cloned the OF repos and tried to compile the project genarator (commandLine app) but I get the following error: 

`: fatal error C1900: Il mismatch between 'P1' version '20150812' and 'P2' version '20130802`

It seems to be related with uriparser.lib which is compiled with "Whole program optimisation" using VS2013. I have fixed this by compiling uriparser myself with VS2015 and disabling the "Whole program optimisation". 

Am I doing something wrong or is this something that needs to be fixed?

Cheers
roxlu

**Comment by arturoc** [comment]
have you downloaded the latest libraries using the download_libs.sh script?

**Comment by roxlu** [comment]
Yes, I've used the "scripts/vs/download_libs.ps1" in a PowerShell.

**Comment by arturoc** [comment]
mmh, that's really strange OF and the examples and tests are building fine in the test servers, not sure what might be going on, are you building for 64 or 32 bits?

**Comment by roxlu** [comment]
I'm building 64bit. Can you confirm if the uriparser lib that  you're using is compiled with or without "whole program optimisation"? (64 bit version).

**Comment by arturoc** [comment]
the library is compiled by the script in this folder:

https://github.com/openframeworks/apothecary/tree/master/apothecary/formulas/uriparser

using the solution next to it

**Comment by roxlu** [comment]
Ok, it seems that "whole program optimisation" is turned on there.  It also seems that the library is indeed compiled with VS2015, though it's using a x86_amd64 feature-set; and I'm using intel. I'm not sure if this could be causing this issue.

**Comment by roxlu** [comment]
Found this link: http://stackoverflow.com/questions/8959973/il-mismatch-between-p1-version-20080116-and-p2-version-20070207

**Comment by chuckleplant** [comment]
Had the same issue, after updating to VS2015 Update 3 it was solved. Only issue I see now is:
```
Warning	LNK4075	ignoring '/INCREMENTAL' due to '/LTCG' specification
```

**Comment by bakercp** [comment]
@roxlu  does @chuckleplant 's solution fix this?
