### ISSUE TITLE
included Poco lib files not working on Ubuntu 15.10 64bit

### ISSUE THREAD

**Issue by frauzufall** [openframeworks/openFrameworks#4863]
With the included Poco lib files I get errors like these when compiling apps:

    ofUtils.cpp:(.text+0x812c): undefined reference to `Poco::URI::URI(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
    ofUtils.cpp:(.text+0x816a): undefined reference to `Poco::URI::setQuery(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
    ofUtils.cpp:(.text+0x8196): undefined reference to `Poco::URI::toString[abi:cxx11]() const'
    ofUtils.cpp:(.text+0x8318): undefined reference to `Poco::URI::toString[abi:cxx11]() const'

To resolve this, I have to delete the content of ```libs/poco/lib/linux64/``` and run the ```.install_dependencies.sh``` script. The new poco lib files are then always displayed as modified files when running ```git status``` which is kind of impractical.

**Comment by arturoc** [comment]
This is because some libraries are not compatible between gcc 4.x and 5.x. Since we've compiled libraries using 4.x they won't be compatible with 5. it's a pain but there's really no solution for it. once the next ubuntu LTS comes out we'll consider that gcc 5 is the standard and use that to compile the libraries.

I'm also setting up some compile servers that will create the liraries automatically whenever we change the apothecary formulas but the travis servers where they are being compiled are still on ubuntu 14.04 max so they won't be compatible yet

**Comment by frauzufall** [comment]
Thanks for explaining it. Would it be possible that if you compile an app or example and you have incompatible poco lib files, instead of throwing all those errors, it tells you to run ./install_dependencies like it does when other libraries are missing?

**Comment by arturoc** [comment]
mmh, good idea but i don't think so :), this libraries are not installed in the system so there's no way to detect which version they are or something like that. in any case this will be solved once the PR to remove the binaries is merged and everyone has to download or compile the libarries anyway if they are using git.

**Comment by frauzufall** [comment]
Yes I googled a bit but I also couldn't find a way to detect the poco version from the lib files. If the poco libs have to be compiled and will not appear in the git status, I am happy :)

**Comment by arturoc** [comment]
yeah cause it's not even the poco version but the version of the compiler that was used to compile the binaries so it's really tricky, we could look for certain symbols in the binaries but sounds super hacky and this will go anyway soon.  thanks for looking into it1

**Comment by frauzufall** [comment]
That's fine, thank you!
