### ISSUE TITLE
Raspberry Pi 2 fails to compile ofFileUtils on master

### ISSUE THREAD

**Issue by bakercp** [openframeworks/openFrameworks#4147]
Currently Raspberry Pi 2 (and likely RPi 1) fail to compiler on ofFileUtils.cpp:725 because it says `copy` is not a member of `std::filesystem`.

I don't have time to take a deeper look at this, but maybe you know how to fix it off the top of your head @arturoc ?

One solution related to #4146 could be that we install gcc > 4.8 (or maybe 4.9 or 5) and just directly use c++14 filesystem features (which I believe includes std:filesystem) rather than the boost stopgap.

**Comment by arturoc** [comment]
filesystem is not part of c++14 it'll be part of c++17. 

isn't there already a raspberry based on jessie? that should solve all this problems

**Comment by bakercp** [comment]
The standard raspberry pi distro (raspbian) is still based on wheezy.  (https://www.raspberrypi.org/downloads/).  I believe that Ubuntu Mate (which is only compatible with RPI2) os jessie based.  There may also be ways to update the standard wheezy image to jessie ... but I'd strongly advocate that we figure out a solution that supports the "standard" wheezy raspberry pi image that is limited to changes in our scripts (i.e. installing updated gcc, updating the make configs, etc).  I think if we require new users to do a lot of OS modifications or use a custom image we'll lose a really great feature -- that is -- the fact that it is pretty easy to get started with oF and RPI.

**Comment by arturoc** [comment]
can you check which version of boost filesystem it's installed? wheezy should have 1.49 which has copy: http://www.boost.org/doc/libs/1_49_0/libs/filesystem/v3/doc/reference.html#copy

**Comment by bakercp** [comment]
@arturoc my pi is offline for a bit and haven't had a chance to get it back up -- a related report here http://forum.openframeworks.cc/t/cant-compile-master-branch-for-rpi-b/20297/3

**Comment by moebiussurfing** [comment]
Hey @arturoc , just I case it helps.. I am getting this errors too, and after following on the above (my) link of @bakercp, 
I checked my raspberry boost version. You can see the link to see how I done; but it looks like my raspbian has Boost 1.49.

**Comment by bakercp** [comment]
Just FYI, I'm still getting `undefined reference to boost::filesystem3::detail::copy_file(...)` during the linking phase of RPI2.  Got any other tips @arturoc?  I think it's the only thing holding up RPI now.

**Comment by bakercp** [comment]
@arturoc just for debugging's sake, if I comment out that single line and compile with g++4.8 RPI2 runs successfully.

**Comment by arturoc** [comment]
@bakercp can you try to change the std flag for rapsbian to -std=c++0x?  in config.linux.common.mk line 124 there's a sequence that detects the gcc version and uses c++0x through c++14 depending on the compiler. can you fix it to c++0x to see if it fixes the undefined symbol?

**Comment by bakercp** [comment]
Yes, will check it today

**Comment by arturoc** [comment]
i'm getting the same in the server that builds the packages, which also runs debian wheezy, and changing to c++0x doesn0t fix it there. i'll take a look at it from there but it's probably a problem in that package in wheezy. we could recomend using arch linux by now in the PI which works pretty well

**Comment by bakercp** [comment]
I can confirm this is fixed on RPI2.  In the process of testing RPI1.
