### ISSUE TITLE
Semantic Issues in ofxiOs SoundOutputStream.m

### ISSUE THREAD

**Issue by kimasendorf** [openframeworks/openFrameworks#4307]
I just wanted to try the KeyboardExample, used the projectGenerator_ios to create a new project and pasted the code from the example.

I get 2 Semantic Issues in SoundOutputStream.m

In row 111 in AudioStreamBasicDescription ```.mSampleRate = sampleRate``` and in row 115 ```.mChannelsPerFrame = numOfChannels```.

Non-constant-expression cannot be narrowed from type 'NSInteger'...

**Comment by bilderbuchi** [comment]
Which version of OF are you using, and from where (release package, git)?

**Comment by kimasendorf** [comment]
I am using the latest nightly build, downloaded just 1h ago.

http://192.237.185.151/versions/nightly/of_v20150827_ios_nightly.zip

It looks like all examples need the ofxiOS addon so I created new projects including it.

**Comment by bilderbuchi** [comment]
ping @openframeworks/ios

**Comment by dorald** [comment]
this isn't bug ..!
When new project created from projectGenereator for iOS and you have checked ofxiOS addon from then give error on build. Just don't include any 'native' addons when new iOS project from PG created.

I suggest to OF team to remove ofxiOS, ofxAccelerometer and ofxMultiTouch addons from PG_iOS addons list.

**Comment by kimasendorf** [comment]
when i do not include the ofxiOS addon i get Apple Mach-O Linker errors. "_fchmodat"

**Comment by arturoc** [comment]
what ios target are you using? this seems to be an incompatibility between an OF dependency compiled for a newer version of iOS.

**Comment by kimasendorf** [comment]
I am on 10.8 and targeted iPhone Retina (3.5-inch) because it was the default selection.

**Comment by arturoc** [comment]
can try recompiling the dependency that seems to be the problem in your system? in a terminal go to the OF root then:

```
cd scripts/apothecary
./apothecary update boost
```

that will download and recompile a couple of libraries. it seems that the version of some system libraries in 10.8 is missing some symbols that exist in 10.10 so libraries compiled in 10.10 are not compatible with 10.8.

if that works can you send a PR with the compiled libraries? they will end up in `libs/boost` once you run the script so you just need to commit that.

**Comment by kimasendorf** [comment]
I updated boost successfully, created a new project, but the linker errors remain the same:

> Undefined symbols for architecture i386:
  "_fchmodat", referenced from:
      boost::filesystem::detail::permissions(boost::filesystem::path const&, boost::filesystem::perms, boost::system::error_code*) in boost_filesystem.a(operations.o)
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by kimasendorf** [comment]
just realized my deployment target is set to 5.1.1

**Comment by arturoc** [comment]
does it fix it if you change it to something higher? 

i think the problem might come from sharing the libraries between osx and ios, osx might have those symbols while ios won't. not sure what's the solution in these cases. ping @julapy @danoli3

**Comment by kimasendorf** [comment]
nope, changing it doesn't help.

**Comment by arturoc** [comment]
if you compile for the device instead of the simulator does that work?

**Comment by kimasendorf** [comment]
"Xcode cannot run using the selected device."

**Comment by arturoc** [comment]
can you try to recompile with apothecary but for ios like:

```
cd scripts/apothecary
./apothecary -t ios update boost
```

**Comment by kimasendorf** [comment]
The update failed..
> Now strip the binary
strip: for architecture cputype (16777228) cpusubtype (0) object: /Users/kimasendorf/Documents/Development/of_v20150907_ios_release/scripts/apothecary/build/boost/lib/boost/ios/boost_filesystem.a(codecvt_error_category.o) malformed object (unknown load command 1)

**Comment by arturoc** [comment]
can you try with this libraries:

```
https://openframeworks.cc/libs/boost/lib/ios/boost_filesystem.a
https://openframeworks.cc/libs/boost/lib/ios/boost_system.a
```

i've only have 10.9 but it might fix it since i think the problem is in 10.10 from what i've found.

**Comment by arturoc** [comment]
just updated the links which had a typo

**Comment by kimasendorf** [comment]
still the same error..

**Comment by admsyn** [comment]
I can't reproduce the `_fchmodat` linker errors on Xcode 6.4, OS X 10.10, deployment target 5.1.1, iOS 8.4 SDK

Pretty sure `"Xcode cannot run using the selected device."` implies a provisioning profile issue, or something similar.

RE the original issue: it is caused by manually including a duplicate of ofxiOS in the project (somehow?). Resolving the semantic issues with explicit casts just leads to duplicate symbol linker errors as you might expect.

**Comment by kimasendorf** [comment]
@admsyn true, on 10.10 it works fine, the error occurs on 10.8.

**Comment by arturoc** [comment]
@kimasendorf can you check if it compiles in 10.8 now?

**Comment by danoli3** [comment]
Just reviewing this, we shouldn't be building the iOS libs with 10.8.
No iOS development for any devices is possible since February this year with Xcode 5.1.1 and that is the latest Xcode available for 10.8. Also building against 10.8 may cause serious errors due to not being compiled with latest LLVM (This may go both ways).

As stated:

Starting February 1, 2015, new iOS apps uploaded to the App Store must include 64-bit support and be built with the iOS 8 SDK, included in Xcode 6 or later (10.9.4/5 10.10 OSX +). To enable 64-bit in your project, we recommend using the default Xcode build setting of “Standard architectures” to build a single binary with both 32-bit and 64-bit code.
https://developer.apple.com/news/?id=10202014a

10.9.4 / 10.10 should be minimum OSX build for **iOS** for 0.9.
This is probably why people on 10.8 are having so much trouble. 
It's not supposed to work with Xcode 5.1.1. LLVM changed so much since.

**Comment by danoli3** [comment]
Anyways, closing this. @openframeworks/ios Seems isolated to 10.8, which is just a build environment error.

Those types defined in the first post are actually all defined by Apple themselves. So obviously just need to update system to build for iOS
