### ISSUE TITLE
deployExamples produces 11 compile errors on MacOS 10.7.2

### ISSUE THREAD

**Issue by iani** [openframeworks/openFrameworks#813]
Hello, 
I am trying to set up the project files for XCode on a newly cloned openFrameworks on a MacBook running MacOS 10.7.2 with XCode 3.2.5. When doing build and run on deployExamples, I get 11 errors such as: 
error: 'MacSetRect' was not declared in this scope
 (see full details below): 

Could someone please help? 

CompileC build/openFrameworksLib.build/Debug/openFrameworks.build/Objects-normal/i386/ofQuickTimeGrabber.o ../../../openFrameworks/video/ofQuickTimeGrabber.cpp normal i386 c++ com.apple.compilers.gcc.4_2
cd /Users/iani/Documents/projects_ongoing/openFrameworks/openFrameworks/libs/openFrameworksCompiled/project/osx
setenv LANG en_US.US-ASCII
/Developer-3.2.5/usr/bin/gcc-4.2 -x c++ -arch i386 -fmessage-length=0 -pipe -Wno-trigraphs -fpascal-strings -fasm-blocks -Os -ftree-vectorize -msse3 -mssse3 -Wno-deprecated-declarations -Wno-invalid-offsetof -gdwarf-2 -I/Users/iani/Documents/projects_ongoing/openFrameworks/openFrameworks/libs/openFrameworksCompiled/project/osx/build/openFrameworksLib.build/Debug/openFrameworks.build/openFrameworksDebug.hmap -F/Users/iani/Documents/projects_ongoing/openFrameworks/openFrameworks/libs/openFrameworksCompiled/project/osx/../../lib/osx -I/Users/iani/Documents/projects_ongoing/openFrameworks/openFrameworks/libs/openFrameworksCompiled/project/osx/../../lib/osx/include -I../../../../libs/openFrameworks -I../../../../libs/openFrameworks/3d -I../../../../libs/openFrameworks/app -I../../../../libs/openFrameworks/communication -I../../../../libs/openFrameworks/events -I../../../../libs/openFrameworks/gl -I../../../../libs/openFrameworks/graphics -I../../../../libs/openFrameworks/math -I../../../../libs/openFrameworks/sound -I../../../../libs/openFrameworks/types -I../../../../libs/openFrameworks/utils -I../../../../libs/openFrameworks/video -I../../../../libs/poco/include -I../../../../libs/freetype/include -I../../../../libs/freetype/include/freetype2 -I../../../../libs/fmodex/include -I../../../../libs/glew/include -I../../../../libs/FreeImage/include -I../../../../libs/tess2/include -I../../../../libs/cairo/include/cairo -I../../../../libs/rtaudio/include -I/Users/iani/Documents/projects_ongoing/openFrameworks/openFrameworks/libs/openFrameworksCompiled/project/osx/build/openFrameworksLib.build/Debug/openFrameworks.build/DerivedSources/i386 -I/Users/iani/Documents/projects_ongoing/openFrameworks/openFrameworks/libs/openFrameworksCompiled/project/osx/build/openFrameworksLib.build/Debug/openFrameworks.build/DerivedSources -D__MACOSX_CORE__ -lpthread -c /Users/iani/Documents/projects_ongoing/openFrameworks/openFrameworks/libs/openFrameworksCompiled/project/osx/../../../openFrameworks/video/ofQuickTimeGrabber.cpp -o /Users/iani/Documents/projects_ongoing/openFrameworks/openFrameworks/libs/openFrameworksCompiled/project/osx/build/openFrameworksLib.build/Debug/openFrameworks.build/Objects-normal/i386/ofQuickTimeGrabber.o

/Users/iani/Documents/projects_ongoing/openFrameworks/openFrameworks/libs/openFrameworksCompiled/project/osx/../../../openFrameworks/video/ofQuickTimeGrabber.cpp: In member function 'virtual bool ofQuickTimeGrabber::initGrabber(int, int)':
/Users/iani/Documents/projects_ongoing/openFrameworks/openFrameworks/libs/openFrameworksCompiled/project/osx/../../../openFrameworks/video/ofQuickTimeGrabber.cpp:109: error: 'MacSetRect' was not declared in this scope
/Users/iani/Documents/projects_ongoing/openFrameworks/openFrameworks/libs/openFrameworksCompiled/project/osx/../../../openFrameworks/video/ofQuickTimeGrabber.cpp:125: error: 'GetGWorldPixMap' was not declared in this scope
/Users/iani/Documents/projects_ongoing/openFrameworks/openFrameworks/libs/openFrameworksCompiled/project/osx/../../../openFrameworks/video/ofQuickTimeGrabber.cpp:125: error: 'LockPixels' was not declared in this scope
/Users/iani/Documents/projects_ongoing/openFrameworks/openFrameworks/libs/openFrameworksCompiled/project/osx/../../../openFrameworks/video/ofQuickTimeGrabber.cpp:126: error: 'SetGWorld' was not declared in this scope

CompileC build/openFrameworksLib.build/Debug/openFrameworks.build/Objects-normal/i386/ofQuickTimePlayer.o ../../../openFrameworks/video/ofQuickTimePlayer.cpp normal i386 c++ com.apple.compilers.gcc.4_2
cd /Users/iani/Documents/projects_ongoing/openFrameworks/openFrameworks/libs/openFrameworksCompiled/project/osx
setenv LANG en_US.US-ASCII
/Developer-3.2.5/usr/bin/gcc-4.2 -x c++ -arch i386 -fmessage-length=0 -pipe -Wno-trigraphs -fpascal-strings -fasm-blocks -Os -ftree-vectorize -msse3 -mssse3 -Wno-deprecated-declarations -Wno-invalid-offsetof -gdwarf-2 -I/Users/iani/Documents/projects_ongoing/openFrameworks/openFrameworks/libs/openFrameworksCompiled/project/osx/build/openFrameworksLib.build/Debug/openFrameworks.build/openFrameworksDebug.hmap -F/Users/iani/Documents/projects_ongoing/openFrameworks/openFrameworks/libs/openFrameworksCompiled/project/osx/../../lib/osx -I/Users/iani/Documents/projects_ongoing/openFrameworks/openFrameworks/libs/openFrameworksCompiled/project/osx/../../lib/osx/include -I../../../../libs/openFrameworks -I../../../../libs/openFrameworks/3d -I../../../../libs/openFrameworks/app -I../../../../libs/openFrameworks/communication -I../../../../libs/openFrameworks/events -I../../../../libs/openFrameworks/gl -I../../../../libs/openFrameworks/graphics -I../../../../libs/openFrameworks/math -I../../../../libs/openFrameworks/sound -I../../../../libs/openFrameworks/types -I../../../../libs/openFrameworks/utils -I../../../../libs/openFrameworks/video -I../../../../libs/poco/include -I../../../../libs/freetype/include -I../../../../libs/freetype/include/freetype2 -I../../../../libs/fmodex/include -I../../../../libs/glew/include -I../../../../libs/FreeImage/include -I../../../../libs/tess2/include -I../../../../libs/cairo/include/cairo -I../../../../libs/rtaudio/include -I/Users/iani/Documents/projects_ongoing/openFrameworks/openFrameworks/libs/openFrameworksCompiled/project/osx/build/openFrameworksLib.build/Debug/openFrameworks.build/DerivedSources/i386 -I/Users/iani/Documents/projects_ongoing/openFrameworks/openFrameworks/libs/openFrameworksCompiled/project/osx/build/openFrameworksLib.build/Debug/openFrameworks.build/DerivedSources -D__MACOSX_CORE__ -lpthread -c /Users/iani/Documents/projects_ongoing/openFrameworks/openFrameworks/libs/openFrameworksCompiled/project/osx/../../../openFrameworks/video/ofQuickTimePlayer.cpp -o /Users/iani/Documents/projects_ongoing/openFrameworks/openFrameworks/libs/openFrameworksCompiled/project/osx/build/openFrameworksLib.build/Debug/openFrameworks.build/Objects-normal/i386/ofQuickTimePlayer.o

/Users/iani/Documents/projects_ongoing/openFrameworks/openFrameworks/libs/openFrameworksCompiled/project/osx/../../../openFrameworks/video/ofQuickTimePlayer.cpp: In destructor 'virtual ofQuickTimePlayer::~ofQuickTimePlayer()':
/Users/iani/Documents/projects_ongoing/openFrameworks/openFrameworks/libs/openFrameworksCompiled/project/osx/../../../openFrameworks/video/ofQuickTimePlayer.cpp:142: error: 'DisposeGWorld' was not declared in this scope
/Users/iani/Documents/projects_ongoing/openFrameworks/openFrameworks/libs/openFrameworksCompiled/project/osx/../../../openFrameworks/video/ofQuickTimePlayer.cpp: In member function 'void ofQuickTimePlayer::createImgMemAndGWorld()':
/Users/iani/Documents/projects_ongoing/openFrameworks/openFrameworks/libs/openFrameworksCompiled/project/osx/../../../openFrameworks/video/ofQuickTimePlayer.cpp:249: error: 'GetGWorldPixMap' was not declared in this scope
/Users/iani/Documents/projects_ongoing/openFrameworks/openFrameworks/libs/openFrameworksCompiled/project/osx/../../../openFrameworks/video/ofQuickTimePlayer.cpp:249: error: 'LockPixels' was not declared in this scope
/Users/iani/Documents/projects_ongoing/openFrameworks/openFrameworks/libs/openFrameworksCompiled/project/osx/../../../openFrameworks/video/ofQuickTimePlayer.cpp:250: error: 'SetGWorld' was not declared in this scope
/Users/iani/Documents/projects_ongoing/openFrameworks/openFrameworks/libs/openFrameworksCompiled/project/osx/../../../openFrameworks/video/ofQuickTimePlayer.cpp: In member function 'virtual bool ofQuickTimePlayer::loadMovie(std::string)':
/Users/iani/Documents/projects_ongoing/openFrameworks/openFrameworks/libs/openFrameworksCompiled/project/osx/../../../openFrameworks/video/ofQuickTimePlayer.cpp:295: error: 'DisposeGWorld' was not declared in this scope
