### ISSUE TITLE
Problem with ndiswrapper and install_dependencies.sh on LMDE; 

### ISSUE THREAD

**Issue by Tinkerer-** [openframeworks/openFrameworks#2612]
Hello, 
I've installed of8.0 on several computers, running flawless on most. On one Linux (Mint debian edition) I have a problem. This is an x86 machine (Centrino Duo),  and when I run "install_dependencies.sh" I get an error when it wants to do something with ndiswrapper:

``` bash
victor@victort61:~/sources/of_v0.8.0_linux_release/scripts/linux/debian$ sudo ./install_dependencies.sh 
Hit http://www.mirrorservice.org testing InRelease
Hit http://www.mirrorservice.org testing/updates InRelease                                                
Hit http://www.mirrorservice.org testing InRelease                                                        
Hit http://www.mirrorservice.org testing/main i386 Packages/DiffIndex                                     
Ign http://packages.linuxmint.com debian InRelease                                                        
Hit http://www.mirrorservice.org testing/contrib i386 Packages/DiffIndex                                  
Hit http://www.mirrorservice.org testing/non-free i386 Packages/DiffIndex                                 
Hit http://www.mirrorservice.org testing/contrib Translation-en/DiffIndex                                 
Hit http://www.mirrorservice.org testing/main Translation-en/DiffIndex                                    
Hit http://www.mirrorservice.org testing/non-free Translation-en/DiffIndex                                
Hit http://www.mirrorservice.org testing/updates/main i386 Packages                                       
Hit http://www.mirrorservice.org testing/updates/contrib i386 Packages                                    
Hit http://www.mirrorservice.org testing/updates/non-free i386 Packages                                   
Hit http://www.mirrorservice.org testing/updates/contrib Translation-en                                   
Hit http://download.virtualbox.org lenny InRelease                                                        
Ign http://linux.dropbox.com maverick InRelease                                                           
Hit http://www.mirrorservice.org testing/updates/main Translation-en                                      
Hit http://www.mirrorservice.org testing/updates/non-free Translation-en                   
Get:1 http://packages.linuxmint.com debian Release.gpg [198 B]                             
Hit http://www.mirrorservice.org testing/main i386 Packages                                
Hit http://download.virtualbox.org lenny/contrib i386 Packages                             
Get:2 http://linux.dropbox.com maverick Release.gpg [489 B]                                
Hit http://www.mirrorservice.org testing/non-free i386 Packages      
Get:3 http://packages.linuxmint.com debian Release [15.6 kB]                               
Hit http://download.virtualbox.org lenny/non-free i386 Packages                                     
Get:4 http://linux.dropbox.com maverick Release [2,605 B]                                            
Get:5 http://linux.dropbox.com maverick/main i386 Packages [1,148 B]                                      
Get:6 http://packages.linuxmint.com debian/main i386 Packages [21.6 kB]
Get:7 http://packages.linuxmint.com debian/upstream i386 Packages [9,957 B]                               
Get:8 http://packages.linuxmint.com debian/import i386 Packages [53.7 kB]                                 
Ign http://www.mirrorservice.org testing/main Translation-en_US                             
Ign http://www.mirrorservice.org testing/main Translation-en                                              
Ign http://www.mirrorservice.org testing/non-free Translation-en_US                                       
Ign http://www.mirrorservice.org testing/non-free Translation-en                                       
Ign http://linux.dropbox.com maverick/main Translation-en_US                                           
Ign http://linux.dropbox.com maverick/main Translation-en             
Ign http://download.virtualbox.org lenny/contrib Translation-en_US
Ign http://download.virtualbox.org lenny/contrib Translation-en
Ign http://download.virtualbox.org lenny/non-free Translation-en_US
Ign http://download.virtualbox.org lenny/non-free Translation-en
Ign http://packages.linuxmint.com debian/import Translation-en_US                                         
Ign http://packages.linuxmint.com debian/import Translation-en                                            
Ign http://packages.linuxmint.com debian/main Translation-en_US                                           
Ign http://packages.linuxmint.com debian/main Translation-en                                              
Ign http://packages.linuxmint.com debian/upstream Translation-en_US                                       
Ign http://packages.linuxmint.com debian/upstream Translation-en                                          
Fetched 105 kB in 8s (12.9 kB/s)                                                                          
Reading package lists... Done
detecting latest gstreamer version
Package: libgstreamer1.0-dev
Source: gstreamer1.0
Version: 1.0.8-1
Installed-Size: 3767
Maintainer: Maintainers of GStreamer packages <pkg-gstreamer-maintainers@lists.alioth.debian.org>
Architecture: i386
Depends: libgstreamer1.0-0 (= 1.0.8-1), libc6-dev | libc-dev, pkg-config, libglib2.0-dev, libc6 (>= 2.3.6-6~), libglib2.0-0 (>= 2.32), gir1.2-gstreamer-1.0 (= 1.0.8-1)
Recommends: debhelper
Suggests: gstreamer1.0-doc
Description-en: GStreamer core development files
 GStreamer is a streaming media framework, based on graphs of filters
 which operate on media data.  Applications using this library can do
 anything from real-time sound processing to playing videos, and just
 about anything else media-related.  Its plugin-based architecture means
 that new data types or processing capabilities can be added simply by
 installing new plug-ins.
 .
 This package contains development files for the core library and
 elements.
Description-md5: de1692260510350a48f76ec91eae40a9
Homepage: http://gstreamer.freedesktop.org
Tag: devel::library, role::devel-lib
Section: libdevel
Priority: optional
Filename: pool/main/g/gstreamer1.0/libgstreamer1.0-dev_1.0.8-1_i386.deb
Size: 1164916
MD5sum: 1862556ce1627a87377e0ec28f31715c
SHA1: 5197de4675f6ef52f4ac71f444fba347e76f34a8
SHA256: a97147d2b1978d8f365ff9734e921922997f025ee90ea2a0e3de5fb5ed63f1ac

selecting gstreamer 1.0
installing OF dependencies
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'libsndfile1-dev' instead of 'libsndfile-dev'
libasound2-dev is already the newest version.
libcairo2-dev is already the newest version.
freeglut3-dev is already the newest version.
libfreeimage-dev is already the newest version.
libfreetype6-dev is already the newest version.
g++ is already the newest version.
libglew-dev is already the newest version.
libgtk2.0-dev is already the newest version.
libdrm-dev is already the newest version.
libglu1-mesa-dev is already the newest version.
libraw1394-dev is already the newest version.
libsndfile1-dev is already the newest version.
libxmu-dev is already the newest version.
libxxf86vm-dev is already the newest version.
python-lxml is already the newest version.
python-lxml set to manually installed.
libgl1-mesa-dev is already the newest version.
libopenal-dev is already the newest version.
libssl-dev is already the newest version.
portaudio19-dev is already the newest version.
libpulse-dev is already the newest version.
libudev-dev is already the newest version.
python-argparse is already the newest version.
python-argparse set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 6 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue [Y/n]? Y
Setting up ndiswrapper-dkms (1.58-2) ...
Removing old ndiswrapper-1.58 DKMS files...

------------------------------
Deleting module version: 1.58
completely from the DKMS tree.
------------------------------
Done.
Loading new ndiswrapper-1.58 DKMS files...
Building for 3.2.0-4-486 and 3.10-2-486
Building initial module for 3.2.0-4-486
Error! Bad return status for module build on kernel: 3.2.0-4-486 (i686)
Consult /var/lib/dkms/ndiswrapper/1.58/build/make.log for more information.
dpkg: error processing ndiswrapper-dkms (--configure):
 subprocess installed post-installation script returned error exit status 10
Errors were encountered while processing:
 ndiswrapper-dkms
E: Sub-process /usr/bin/dpkg returned an error code (1)
error installing dependencies, there could be an error with your internet connection
if the error persists, please report an issue in github: http://github.com/openframeworks/openFrameworks/issues
victor@victort61:~/sources/of_v0.8.0_linux_release/scripts/linux/debian$ 

```

The content of /var/lib/kms/ndiswrapper/1.58/build/make.log is

```
DKMS make.log for ndiswrapper-1.58 for kernel 3.2.0-4-486 (i686)
Sat Oct 12 22:09:49 CEST 2013
make: Entering directory `/usr/src/linux-headers-3.2.0-4-486'
  LD      /var/lib/dkms/ndiswrapper/1.58/build/built-in.o
  MKEXPORT /var/lib/dkms/ndiswrapper/1.58/build/crt_exports.h
  MKEXPORT /var/lib/dkms/ndiswrapper/1.58/build/hal_exports.h
  MKEXPORT /var/lib/dkms/ndiswrapper/1.58/build/ndis_exports.h
  MKEXPORT /var/lib/dkms/ndiswrapper/1.58/build/ntoskernel_exports.h
  MKEXPORT /var/lib/dkms/ndiswrapper/1.58/build/ntoskernel_io_exports.h
  MKEXPORT /var/lib/dkms/ndiswrapper/1.58/build/rtl_exports.h
  MKEXPORT /var/lib/dkms/ndiswrapper/1.58/build/usb_exports.h
  CC [M]  /var/lib/dkms/ndiswrapper/1.58/build/crt.o
  CC [M]  /var/lib/dkms/ndiswrapper/1.58/build/hal.o
  CC [M]  /var/lib/dkms/ndiswrapper/1.58/build/iw_ndis.o
  CC [M]  /var/lib/dkms/ndiswrapper/1.58/build/loader.o
  CC [M]  /var/lib/dkms/ndiswrapper/1.58/build/ndis.o
  CC [M]  /var/lib/dkms/ndiswrapper/1.58/build/ntoskernel.o
  CC [M]  /var/lib/dkms/ndiswrapper/1.58/build/ntoskernel_io.o
  CC [M]  /var/lib/dkms/ndiswrapper/1.58/build/pe_linker.o
  CC [M]  /var/lib/dkms/ndiswrapper/1.58/build/pnp.o
  CC [M]  /var/lib/dkms/ndiswrapper/1.58/build/proc.o
/var/lib/dkms/ndiswrapper/1.58/build/proc.c:35:47: error: unknown type name ‘kuid_t’
/var/lib/dkms/ndiswrapper/1.58/build/proc.c:35:59: error: unknown type name ‘kgid_t’
/var/lib/dkms/ndiswrapper/1.58/build/proc.c: In function ‘procfs_write_ndis_settings’:
/var/lib/dkms/ndiswrapper/1.58/build/proc.c:291:9: error: implicit declaration of function ‘file_inode’ [-Werror=implicit-function-declaration]
/var/lib/dkms/ndiswrapper/1.58/build/proc.c:291:9: warning: passing argument 1 of ‘PDE_DATA’ makes pointer from integer without a cast [enabled by default]
/var/lib/dkms/ndiswrapper/1.58/build/proc.c:30:21: note: expected ‘const struct inode *’ but argument is of type ‘int’
/var/lib/dkms/ndiswrapper/1.58/build/proc.c: In function ‘wrap_procfs_add_ndis_device’:
/var/lib/dkms/ndiswrapper/1.58/build/proc.c:420:2: error: implicit declaration of function ‘proc_set_user’ [-Werror=implicit-function-declaration]
cc1: some warnings being treated as errors
make[3]: *** [/var/lib/dkms/ndiswrapper/1.58/build/proc.o] Error 1
make[2]: *** [_module_/var/lib/dkms/ndiswrapper/1.58/build] Error 2
make[1]: *** [sub-make] Error 2
make: *** [all] Error 2
make: Leaving directory `/usr/src/linux-headers-3.2.0-4-486'
```

Any suggestions?

**Comment by MestreLion** [comment]
This is closed and solved, but just shedding some light on the error @Tinkerer-  has seeing:

You were trying to compile ndiswrapper, which references `kuid_t`, on a Linux Kernel **3.2.0**-4-486. But `kuid_t`, along with its definition file `uidgid.h`, were only introduced in Linux Kernel **3.5.0**: https://github.com/torvalds/linux/commits/master/include/linux/uidgid.h

So, an alternative solution would be to either copy `uidgid.h` to `/usr/include/linux/` or to replace/typedef all `kuid_t` references in ndiswrapper code to `uid_t` (just like `uidgid.h` does). That would (possibly) allow ndiswrapper to compile on a 3.2 kernel.

I had exactly the same problem trying to compile an MT7601 driver, and the 2nd approach worked beautifully.
